spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true&requireSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration-minutes: ${ACCESS_TOKEN_EXPIRATION_MINUTES}

auth:
  refresh:
    expiration-days: ${REFRESH_TOKEN_EXPIRATION_DAYS}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when-authorized

monitoring:
  discord:
    error-webhook-url: ${DISCORD_WEBHOOK_URL}
    enabled: true
    include-logs: true          # MVP 단계라 true
    include-stacktrace: true    # MVP 단계라 true

cafe24:
  api:
    oauth-url: ${CAFE24_API_OAUTH_URL}
    base-url: ${CAFE24_API_BASE_URL}
    client-id: ${CAFE24_API_CLIENT_ID}
    client-secret: ${CAFE24_API_CLIENT_SECRET}
    redirect-uri: ${CAFE24_API_REDIRECT_URI}
    scope: ${CAFE24_API_SCOPE}
