spring:
  application:
    name: inventory-server
  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

cafe24:
  api:
    oauth-url: ${CAFE24_API_OAUTH_URL}
    base-url: ${CAFE24_API_BASE_URL}
    client-id: ${CAFE24_API_CLIENT_ID}
    client-secret: ${CAFE24_API_CLIENT_SECRET}
    redirect-uri: ${CAFE24_API_REDIRECT_URI}
    scope: ${CAFE24_API_SCOPE}
    oauth-success-redirect-url: ${CAFE24_OAUTH_SUCCESS_REDIRECT_URL}
